name: Jednorazowy test Garmina

on:
  workflow_dispatch:  # pozwala uruchomić ręcznie z poziomu GitHub UI

jobs:
  test-garmin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install garminconnect

      - name: Run Garmin test script
        env:
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
        run: |
          echo "import json
import datetime
from garminconnect import Garmin

client = Garmin('${GARMIN_USER}', '${GARMIN_PASS}')
client.login()
today = datetime.date.today()
stats = client.get_stats(today.isoformat())
print(json.dumps(stats, indent=2))
" > test_garmin.py
          python test_garmin.py
